### ISSUE TITLE
Google Verification Code Stored in a Public GitHub Repository

### ISSUE THREAD

**Issue by naclcaleb** [frankarendpoth/frankarendpoth.github.io#2]
Your Google site verification code is completely visible and easily accessed by any person viewing this repository. This is a security flaw, and you may wish to fix it. 

Of course it is up to you what you do with your verification code, but I would highly suggest taking it off of the repo.

**Comment by frankarendpoth** [comment]
Yeah, that is true. I suppose when I started the site I wasn't too worried
about people messing with my Google information, but now that I have a bit
more traffic it is more of a problem. Thanks for your concern and bringing
it to my attention.

**Comment by Midacts** [comment]
I'm not sure how you could get it out of the repo history now that it has been committed?

(I've ran into similar scenarios in the past and have been uncertain on how to wipe out any traces of it in the commit history).
